# Shared by every machine. Personal-only and work-only apps live in
# .Brewfile.personal and .Brewfile.work.
brew "gh"
brew "mise"
brew "telnet"
brew "tig"
brew "tmux"
brew "tree"
brew "unar"
brew "wget"

cask "1password"
cask "1password-cli"
cask "font-source-code-pro"
cask "google-chrome"
cask "macvim-app"
cask "raycast"
cask "visual-studio-code"

vscode "firsttris.vscode-jest-runner"
vscode "fuadpashayev.bottom-terminal"
vscode "hverlin.mise-vscode"
vscode "l-igh-t.vscode-theme-seti-folder"
vscode "ms-vscode.live-server"
vscode "tombi-toml.tombi" # recommended by "hverlin.mise-vscode"
